name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-cpp:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install -y wget unzip cmake libgtest-dev
      - name: Fetch libtorch
        run: wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.0.1%2Bcpu.zip && unzip libtorch-cxx11-abi-shared-with-deps-2.0.1+cpu.zip
      - name: Run format checking
        run: bash scripts/run_format.sh -c
      - name: Run tests
        run: bash scripts/run_cpp_tests.sh

  linting-code-coverage-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install test dependencies
      run: |
        python -m pip install -r requirements-dev.txt
    - name: Running flake8
      run: |
        flake8 .
    - name: Running isort
      run: |
        isort . --check
    - name: Running black
      run: |
        black . --check --line-length=128
    - name: Running mypy
      run: |
        mypy .
    - name: Install pytorch
      run: |
        python -m pip install torch==2.0.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Code coverage
      run: |
        python -m pip install --no-build-isolation -e .
        pytest --cov=pt_seq_nms --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest]
        pytorch-version: ['1.13.1', '2.0.1']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pytorch
      run: |
        python -m pip install torch==${{ matrix.pytorch-version }}+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Install package
      run: |
        python -m pip install -r requirements-dev.txt
        python -m pip install --no-build-isolation .
    - name: Run unit tests
      run: |
        pytest tests/

  windows-test:
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install pytorch
      run: |
        python -m pip install torch==2.0.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Install package
      run: |
        python -m pip install -r requirements-dev.txt
        python -m pip install --no-build-isolation .
      env:
        DISTUTILS_USE_SDK: 1
    - name: Run unit tests
      run: pytest tests/
