name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-cpp:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y wget unzip cmake libgtest-dev
      - name: Fetch libtorch
        run: wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.10.1%2Bcpu.zip && unzip libtorch-cxx11-abi-shared-with-deps-1.10.1+cpu.zip
      - name: Run format checking
        run: bash scripts/run_format.sh -c
      - name: Run tests
        run: bash scripts/run_cpp_tests.sh
